version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_EXPRESS_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_EXPRESS_ROOT_PASSWORD}
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - mongodb_network
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_EXPRESS_MONGODB_SERVER}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=${MONGO_EXPRESS_MONGODB_ENABLE_ADMIN}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_MONGODB_ADMINPASSWORD}

    depends_on:
      - mongodb
    networks:
      - mongodb_network
    ports:
      - 8081:8081
    restart: unless-stopped

volumes:
  mongodb-data:
    name: mongodb-data
networks:
  mongodb_network:
    name: mongodb_network
